//
//  ArticleWireframe.swift
//  TheVargo
//
//  Created by Andre Souza on 06/07/2018.
//  Copyright (c) 2018 AndreSamples. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ArticleWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(type: .feed)

    // MARK: - Module setup -

    func configureModule(with viewController: ArticleViewController) {
        let interactor = ArticleInteractor()
        let presenter = ArticlePresenter(wireframe: self, view: viewController, interactor: interactor)
        viewController.presenter = presenter
    }

    // MARK: - Transitions -

    func show(with transition: Transition, animated: Bool = true) {
        let moduleViewController = _storyboard.instantiateViewController(ofType: ArticleViewController.self)
        configureModule(with: moduleViewController)

        show(moduleViewController, with: transition, animated: animated)
    }
}

// MARK: - Extensions -

extension ArticleWireframe: ArticleWireframeInterface {

    func navigate(to option: ArticleNavigationOption) {
    }
}
