//
//  ArticleViewController.swift
//  TheVargo
//
//  Created by Andre Souza on 06/07/2018.
//  Copyright (c) 2018 AndreSamples. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ArticleViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: ArticlePresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }
}

// MARK: - Extensions -

extension ArticleViewController: ArticleViewInterface {
}
