//
//  ArticleInterfaces.swift
//  TheVargo
//
//  Created by Andre Souza on 06/07/2018.
//  Copyright (c) 2018 AndreSamples. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum ArticleNavigationOption {
}

protocol ArticleWireframeInterface: WireframeInterface {
    func navigate(to option: ArticleNavigationOption)
}

protocol ArticleViewInterface: ViewInterface {
}

protocol ArticlePresenterInterface: PresenterInterface {
}

protocol ArticleInteractorInterface: InteractorInterface {
}
