//
//  ArticlePresenter.swift
//  TheVargo
//
//  Created by Andre Souza on 06/07/2018.
//  Copyright (c) 2018 AndreSamples. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ArticlePresenter {

    // MARK: - Private properties -

    private unowned let _view: ArticleViewInterface
    private let _interactor: ArticleInteractorInterface
    private let _wireframe: ArticleWireframeInterface

    // MARK: - Lifecycle -

    init(wireframe: ArticleWireframeInterface,
         view: ArticleViewInterface,
         interactor: ArticleInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension ArticlePresenter: ArticlePresenterInterface {
}
