//
//  FeedDetailInterfaces.swift
//  TheVargo
//
//  Created by Andre Souza on 09/07/2018.
//  Copyright (c) 2018 AndreSamples. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum FeedDetailNavigationOption {
}

protocol FeedDetailWireframeInterface: WireframeInterface {
    func navigate(to option: FeedDetailNavigationOption)
}

protocol FeedDetailViewInterface: ViewInterface {
    func open(_ activityViewController: UIActivityViewController)
    func setBookmarked()
    func showfeedContent(_ item: FeedItemDetailInterface)
}

protocol FeedDetailPresenterInterface: PresenterInterface {
    func didPressPlay()
    func didPressShare()
    func didPressBookmark()
    func didPressUrl()
}

protocol FeedDetailInteractorInterface: InteractorInterface {
    
}

protocol FeedItemDetailInterface: FeedListItemInterface {
    var screenTitle: String { get }
    var authorTitle: String? { get }
    var author: String? { get }
    var urlTitle: String? { get }
    var urlDescription: String? { get }
    var url: String? { get }
    var date: String? { get }
}
