//
//  FeedDetailWireframe.swift
//  TheVargo
//
//  Created by Andre Souza on 09/07/2018.
//  Copyright (c) 2018 AndreSamples. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class FeedDetailWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(type: .feed)

    // MARK: - Module setup -

    func configureModule(with viewController: FeedDetailViewController) {
        let interactor = FeedDetailInteractor()
        let presenter = FeedDetailPresenter(wireframe: self, view: viewController, interactor: interactor)
        viewController.presenter = presenter
    }

    // MARK: - Transitions -

    func show(with transition: Transition, animated: Bool = true) {
        let moduleViewController = _storyboard.instantiateViewController(ofType: FeedDetailViewController.self)
        configureModule(with: moduleViewController)

        show(moduleViewController, with: transition, animated: animated)
    }
}

// MARK: - Extensions -

extension FeedDetailWireframe: FeedDetailWireframeInterface {

    func navigate(to option: FeedDetailNavigationOption) {
    }
}
