//
//  FeedListPresenter.swift
//  TheVargo
//
//  Created by Andre Souza on 09/07/2018.
//  Copyright (c) 2018 AndreSamples. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class FeedListPresenter {

    // MARK: - Private properties -

    private unowned let _view: FeedListViewInterface
    private let _interactor: FeedListInteractorInterface
    private let _wireframe: FeedListWireframeInterface
    
    private var feed: Feed = Feed() {
        didSet {
            _view.reloadData()
        }
    }

    // MARK: - Lifecycle -

    init(wireframe: FeedListWireframeInterface,
         view: FeedListViewInterface,
         interactor: FeedListInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension FeedListPresenter: FeedListPresenterInterface {
    
    func numberOfSections() -> Int {
        return 1
    }
    
    func numberOrItems(in section: Int) -> Int {
        return feed.items?.count ?? 0
    }
    
    func item(at indexPath: IndexPath) -> FeedItemInterface? {
        return feed.items?[indexPath.row]
    }
    
    func didSelectItem(at indexPath: IndexPath) {
        if let item = feed.items?[indexPath.row] {
            _wireframe.navigate(to: .detail(item))
        }
    }
    
    
    
    
}
