//
//  FeedListViewController.swift
//  TheVargo
//
//  Created by Andre Souza on 09/07/2018.
//  Copyright (c) 2018 AndreSamples. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class FeedListViewController: VBaseViewController {

    // MARK: - Public properties -

    var presenter: FeedListPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }

    @IBAction func touchButton(_ sender: Any) {
        presenter.didPressButton()
    }
    
    
}

// MARK: - Extensions -

extension FeedListViewController: FeedListViewInterface {
    
    func showArticles(_ articles: [Article]) {
        //TODO
    }
    
    func showLoading(_ loading: Bool) {
        showLoadingView(loading)
    }
    
    func showError(message: String, target: Any, action: Selector) {
        showError(message: message, target: target, action: action)
    }
    
}
