//
//  FeedListInterfaces.swift
//  TheVargo
//
//  Created by Andre Souza on 09/07/2018.
//  Copyright (c) 2018 AndreSamples. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum FeedListNavigationOption {
    case detail
    
//    var viewController: UIViewController {
//        switch self {
//        case .detail:
//            return
//        }
//    }
}

protocol FeedListWireframeInterface: WireframeInterface {
    func navigate(to option: FeedListNavigationOption)
}

protocol FeedListViewInterface: ViewInterface {
    func showArticles(_ articles: [Article])
    func showLoading(_ loading: Bool)
    func showError(message: String, target: Any, action:Selector)
}

protocol FeedListPresenterInterface: PresenterInterface {
}

protocol FeedListInteractorInterface: InteractorInterface {
}
