//
//  FeedListInteractor.swift
//  TheVargo
//
//  Created by Andre Souza on 09/07/2018.
//  Copyright (c) 2018 AndreSamples. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class FeedListInteractor {
}

// MARK: - Extensions -

extension FeedListInteractor: FeedListInteractorInterface {
}
